const workoutNames = [
  "3/4 sit-up",
  "air bike",
  "45° side bend",
  "ankle circles",
  "all fours squad stretch",
  "archer pull up",
  "alternate lateral pulldown",
  "alternate heel touchers",
  "arm slingers hanging straight legs",
  "assisted hanging knee raise",
  "arms overhead full sit-up (male)",
  "archer push up",
  "assisted chest dip (kneeling)",
  "arms apart circular toe touch (male)",
  "arm slingers hanging bent knee legs",
  "assisted lying leg raise with throw down",
  "assisted motion russian twist",
  "assisted seated pectoralis major stretch with stability ball",
  "assisted lying calves stretch",
  "assisted prone rectus femoris stretch",
  "assisted lying glutes stretch",
  "assisted lying gluteus and piriformis stretch",
  "assisted parallel close grip pull-up",
  "assisted hanging knee raise with throw down",
  "assisted prone hamstring",
  "assisted pull-up",
  "assisted prone lying quads stretch",
  "assisted lying leg raise with lateral throw down",
  "assisted triceps dip (kneeling)",
  "assisted sit-up",
  "assisted wide-grip chest dip (kneeling)",
  "assisted side lying adductor stretch",
  "back pec stretch",
  "back and forth step",
  "assisted standing pull-up",
  "astride jumps (male)",
  "assisted standing triceps extension (with towel)",
  "backward jump",
  "back extension on exercise ball",
  "band alternating biceps curl",
  "back lever",
  "assisted standing chin-up",
  "balance board",
  "band alternating v-up",
  "band assisted pull-up",
  "band assisted wheel rollerout",
  "band bent-over hip extension",
  "band bench press",
  "band bicycle crunch",
  "band close-grip pulldown",
  "band hip lift",
  "band close-grip push-up",
  "band concentration curl",
  "band fixed back close grip pulldown",
  "band fixed back underhand pulldown",
  "band front lateral raise",
  "band front raise",
  "band horizontal pallof press",
  "band one arm standing low row",
  "band kneeling one arm pulldown",
  "band one arm overhead biceps curl",
  "band push sit-up",
  "band lying straight leg raise",
  "band pull through",
  "band one arm twisting seated row",
  "band one arm single leg split squat",
  "band kneeling twisting crunch",
  "band jack knife sit-up",
  "band lying hip internal rotation",
  "band one arm twisting chest press",
  "band seated twist",
  "band reverse fly",
  "band shoulder press",
  "band single leg split squat",
  "band shrug",
  "band standing crunch",
  "band squat",
  "band reverse wrist curl",
  "band side triceps extension",
  "band single leg calf raise",
  "band squat row",
  "band single leg reverse calf raise",
  "band standing rear delt row",
  "band seated hip internal rotation",
  "band step-up",
  "band wrist curl",
  "band twisting overhead press",
  "band stiff leg deadlift",
  "band straight back stiff leg deadlift",
  "band two legs calf raise - (band under both legs) v. 2",
  "band vertical pallof press",
  "band underhand pulldown",
  "band straight leg deadlift",
  "band standing twisting crunch",
  "band v-up",
  "band y-raise",
  "barbell alternate biceps curl",
  "barbell bench front squat",
  "barbell bench press",
  "barbell bench squat",
  "barbell bent over row",
  "barbell bent arm pullover",
  "barbell biceps curl (with arm blaster)",
  "barbell deadlift",
  "barbell curl",
  "barbell clean-grip front squat",
  "barbell clean and press",
  "barbell close-grip bench press",
  "barbell drag curl",
  "barbell decline bent arm pullover",
  "barbell decline pullover",
  "barbell floor calf raise",
  "barbell decline close grip to skull press",
  "barbell decline wide-grip press",
  "barbell decline bench press",
  "barbell decline wide-grip pullover",
  "barbell full squat (back pov)",
  "barbell front raise",
  "barbell glute bridge two legs on bench (male)",
  "barbell front raise and pullover",
  "barbell hack squat",
  "barbell full squat",
  "barbell front squat",
  "barbell front chest squat",
  "barbell full squat (side pov)",
  "barbell good morning",
  "barbell guillotine bench press",
  "barbell full zercher squat",
  "barbell glute bridge",
  "barbell lateral lunge",
  "barbell jefferson squat",
  "barbell high bar squat",
  "barbell incline reverse-grip press",
  "barbell incline bench press",
  "barbell incline close grip bench press",
  "barbell incline row",
  "barbell jm bench press",
  "barbell incline shoulder raise",
  "barbell jump squat",
  "barbell low bar squat",
  "barbell lunge",
  "barbell lying back of the head tricep extension",
  "barbell lying close-grip press",
  "barbell lying lifting (on hip)",
  "barbell lying close-grip triceps extension",
  "barbell lying extension",
  "barbell lying preacher curl",
  "barbell one arm bent over row",
  "barbell lying triceps extension skull crusher",
  "barbell narrow stance squat",
  "barbell lying triceps extension",
  "barbell one arm floor press",
  "barbell overhead squat",
  "barbell one arm side deadlift",
  "barbell one leg squat",
  "barbell palms down wrist curl over a bench",
  "barbell one arm snatch",
  "barbell pendlay row",
  "barbell prone incline curl",
  "barbell press sit-up",
  "barbell rack pull",
  "barbell preacher curl",
  "barbell palms up wrist curl over a bench",
  "barbell rear delt row",
  "barbell pullover",
  "barbell rear delt raise",
  "barbell pin presses",
  "barbell pullover to press",
  "barbell reverse preacher curl",
  "barbell rear lunge v. 2",
  "barbell revers wrist curl v. 2",
  "barbell reverse grip bent over row",
  "barbell reverse grip skullcrusher",
  "barbell rear lunge",
  "barbell reverse curl",
  "barbell reverse grip decline bench press",
  "barbell reverse close-grip bench press",
  "barbell reverse grip incline bench row",
  "barbell reverse grip incline bench press",
  "barbell reverse wrist curl",
  "barbell rollerout",
  "barbell rollerout from bench",
  "barbell romanian deadlift",
  "barbell seated calf raise",
  "barbell seated bradford rocky press",
  "barbell seated behind head military press",
  "barbell seated overhead triceps extension",
  "barbell seated overhead press",
  "barbell seated good morning",
  "barbell seated close grip behind neck triceps extension",
  "barbell seated twist",
  "barbell seated calf raise",
  "barbell seated close-grip concentration curl",
  "barbell single leg deadlift",
  "barbell side split squat v. 2",
  "barbell speed squat",
  "barbell shrug",
  "barbell side bent v. 2",
  "barbell sitted alternate leg raise",
  "barbell single leg split squat",
  "barbell side split squat",
  "barbell split squat v. 2",
  "barbell sitted alternate leg raise (female)",
  "barbell skier",
  "barbell squat jump step rear lunge",
  "barbell standing bradford press",
  "barbell standing close grip curl",
  "barbell standing close grip military press",
  "barbell standing calf raise",
  "barbell standing back wrist curl",
  "barbell standing leg calf raise",
  "barbell squat (on knees)",
  "barbell standing concentration curl",
  "barbell standing rocking leg calf raise",
  "barbell standing overhead triceps extension",
  "barbell standing ab rollerout",
  "barbell standing front raise over head",
  "barbell standing reverse grip curl",
  "barbell straight leg deadlift",
  "barbell standing wide grip biceps curl",
  "barbell step-up",
  "barbell stiff leg good morning",
  "barbell standing wide military press",
  "barbell standing twist",
  "barbell standing wide-grip curl",
  "barbell sumo deadlift",
  "barbell upright row",
  "barbell thruster",
  "barbell upright row v. 2",
  "barbell wide bench press",
  "barbell upright row v. 3",
  "barbell wide reverse grip bench press",
  "barbell wide-grip upright row",
  "barbell wide squat",
  "barbell wrist curl",
  "barbell wrist curl v. 2",
  "bench dip on floor",
  "basic toe touch (male)",
  "bench hip extension",
  "barbell zercher squat",
  "bear crawl",
  "behind head chest stretch",
  "battling ropes",
  "bench dip (knees bent)",
  "biceps narrow pull-ups",
  "biceps leg concentration curl",
  "biceps pull-up",
  "bent knee lying twist (male)",
  "body-up",
  "bench pull-ups",
  "bodyweight drop jump squat",
  "bodyweight incline side plank",
  "bodyweight side lying biceps curl",
  "bodyweight kneeling triceps extension",
  "bodyweight standing calf raise",
  "bodyweight standing close-grip one arm row",
  "bodyweight standing one arm row",
  "bodyweight squatting row",
  "bodyweight squatting row (with towel)",
  "bodyweight standing row (with towel)",
  "bodyweight standing row",
  "bodyweight standing close-grip row",
  "bodyweight standing one arm row (with towel)",
  "butterfly yoga pose",
  "butt-ups",
  "burpee",
  "cable alternate triceps extension",
  "bottoms-up",
  "bridge - mountain climber (cross body)",
  "box jump down with one leg stabilization",
  "cable alternate shoulder press",
  "cable assisted inverse leg curl",
  "cable bench press",
  "cable bar lateral pulldown",
  "cable concentration curl",
  "cable close grip curl",
  "cable concentration extension (on knee)",
  "cable curl",
  "cable decline fly",
  "cable deadlift",
  "cable cross-over lateral pulldown",
  "cable cross-over revers fly",
  "cable cross-over variation",
  "cable drag curl",
  "cable decline seated wide-grip row",
  "cable decline press",
  "cable decline one arm press",
  "cable floor seated wide-grip row",
  "cable forward raise",
  "cable hammer curl (with rope)",
  "cable hip adduction",
  "cable front shoulder raise",
  "cable front raise",
  "cable high pulley overhead tricep extension",
  "cable high row (kneeling)",
  "cable incline bench press",
  "cable judo flip",
  "cable kickback",
  "cable incline triceps extension",
  "cable incline fly",
  "cable incline fly (on stability ball)",
  "cable incline pushdown",
  "cable incline bench row",
  "cable kneeling crunch",
  "cable kneeling rear delt row (with rope) (male)",
  "cable low seated row",
  "cable low fly",
  "cable lateral raise",
  "cable lateral pulldown with v-bar",
  "cable lateral pulldown (with rope attachment)",
  "cable kneeling triceps extension",
  "cable lat pulldown full range of motion",
  "cable lying extension pullover (with rope attachment)",
  "cable lying close-grip curl",
  "cable lying bicep curl",
  "cable lying fly",
  "cable one arm bent over row",
  "cable lying triceps extension v. 2",
  "cable middle fly",
  "cable one arm curl",
  "cable one arm incline press",
  "cable one arm incline fly on exercise ball",
  "cable one arm fly on exercise ball",
  "cable one arm decline chest fly",
  "cable one arm lateral raise",
  "cable one arm lateral bent-over",
  "cable one arm press on exercise ball",
  "cable one arm incline press on exercise ball",
  "cable one arm preacher curl",
  "cable one arm pulldown",
  "cable one arm reverse preacher curl",
  "cable overhead curl",
  "cable overhead curl on exercise ball",
  "cable overhead triceps extension (rope attachment)",
  "cable one arm tricep pushdown",
  "cable palm rotational row",
  "cable one arm straight back high row (kneeling)",
  "cable pulldown (pro lat bar)",
  "cable pushdown (with rope attachment)",
  "cable pulldown",
  "cable preacher curl",
  "cable pushdown",
  "cable pull through (with rope)",
  "cable pulldown bicep curl",
  "cable press on exercise ball",
  "cable pushdown (straight arm) v. 2",
  "cable rear pulldown",
  "cable rear delt row (stirrups)",
  "cable rear drive",
  "cable rear delt row (with rope)",
  "cable reverse one arm curl",
  "cable reverse grip triceps pushdown (sz-bar) (with arm blaster)",
  "cable reverse crunch",
  "cable reverse curl",
  "cable rope extension incline bench row",
  "cable reverse preacher curl",
  "cable reverse-grip straight back seated high row",
  "cable reverse wrist curl",
  "cable reverse-grip pushdown",
  "cable rope elevated seated row",
  "cable rope crossover seated row",
  "cable rope hammer preacher curl",
  "cable rope incline tricep extension",
  "cable rope high pulley overhead tricep extension",
  "cable rope lying on floor tricep extension",
  "cable rope seated row",
  "cable rope one arm hammer preacher curl",
  "cable russian twists (on stability ball)",
  "cable seated high row (v-bar)",
  "cable seated crunch",
  "cable seated one arm alternate row",
  "cable seated chest press",
  "cable seated curl",
  "cable seated twist",
  "cable seated one arm concentration curl",
  "cable seated rear lateral raise",
  "cable seated overhead curl",
  "cable seated shoulder internal rotation",
  "cable seated row",
  "cable seated wide-grip row",
  "cable shoulder press",
  "cable standing calf raise",
  "cable shrug",
  "cable side bend crunch (bosu ball)",
  "cable side bend",
  "cable standing cross-over high reverse fly",
  "cable standing back wrist curl",
  "cable squatting curl",
  "cable standing crunch",
  "cable squat row (with rope attachment)",
  "cable side crunch",
  "cable standing one arm triceps extension",
  "cable standing pulldown (with rope)",
  "cable standing lift",
  "cable standing inner curl",
  "cable standing one leg calf raise",
  "cable standing hip extension",
  "cable standing fly",
  "cable standing row (v-bar)",
  "cable standing crunch (with rope attachment)",
  "cable standing rear delt row (with rope)",
  "cable standing shoulder external rotation",
  "cable standing reverse grip one arm overhead tricep extension",
  "cable straight arm pulldown (with rope)",
  "cable straight arm pulldown",
  "cable standing twist row (v-bar)",
  "cable standing up straight crossovers",
  "cable supine reverse fly",
  "cable straight back seated row",
  "cable thibaudeau kayak row",
  "cable tuck reverse crunch",
  "cable triceps pushdown (v-bar) (with arm blaster)",
  "cable triceps pushdown (v-bar)",
  "cable twist",
  "cable twist (up-down)",
  "cable two arm tricep kickback",
  "cable two arm curl on incline bench",
  "cable twisting pull",
  "cable underhand pulldown",
  "cable wide grip rear pulldown behind neck",
  "cable wrist curl",
  "calf push stretch with hands against wall",
  "cable upper row",
  "cable upper chest crossovers",
  "calf stretch with hands against wall",
  "cable upright row",
  "chest and front of shoulder stretch",
  "cambered bar lying row",
  "chest dip on straight bar",
  "calf stretch with rope",
  "chair leg extended stretch",
  "chest dip (on dip-pull-up cage)",
  "chest stretch with exercise ball",
  "chest dip",
  "captains chair straight leg raise",
  "close-grip push-up (on knees)",
  "close grip chin-up",
  "chest tap push-up (male)",
  "clap push up",
  "circles knee stretch",
  "chin-up",
  "close-grip push-up",
  "chin-ups (narrow parallel grip)",
  "clock push-up",
  "crunch floor",
  "cross body crunch",
  "cocoons",
  "crab twist toe touch",
  "crunch (on stability ball)",
  "crunch (hands overhead)",
  "curl-up",
  "curtsey squat",
  "crunch (on stability ball, arms straight)",
  "cycle cross trainer",
  "decline push-up",
  "dead bug",
  "decline crunch",
  "decline sit-up",
  "diamond push-up",
  "deep push up",
  "donkey calf raise",
  "drop push up",
  "dumbbell alternate biceps curl",
  "dumbbell alternate biceps curl (with arm blaster)",
  "dumbbell alternate preacher curl",
  "dumbbell alternate seated hammer curl",
  "dumbbell alternate hammer preacher curl",
  "dumbbell alternating bicep curl with leg raised on exercise ball",
  "dumbbell alternate side press",
  "dumbbell arnold press v. 2",
  "dumbbell alternating seated bicep curl on exercise ball",
  "dumbbell around pullover",
  "dumbbell arnold press",
  "dumbbell bench press",
  "dumbbell bench seated press",
  "dumbbell bicep curl on exercise ball with leg raised",
  "dumbbell bicep curl with stork stance",
  "dumbbell bicep curl lunge with bowling motion",
  "dumbbell bench squat",
  "dumbbell biceps curl (with arm blaster)",
  "dumbbell burpee",
  "dumbbell bent over row",
  "dumbbell biceps curl reverse",
  "dumbbell clean",
  "dumbbell biceps curl",
  "dumbbell biceps curl squat",
  "dumbbell biceps curl v sit on bosu ball",
  "dumbbell decline fly",
  "dumbbell cuban press",
  "dumbbell close-grip press",
  "dumbbell decline bench press",
  "dumbbell concentration curl",
  "dumbbell contralateral forward lunge",
  "dumbbell deadlift",
  "dumbbell close grip press",
  "dumbbell cross body hammer curl v. 2",
  "dumbbell cross body hammer curl",
  "dumbbell cuban press v. 2",
  "dumbbell decline one arm fly",
  "dumbbell decline hammer press",
  "dumbbell decline shrug",
  "dumbbell decline one arm hammer press",
  "dumbbell decline shrug v. 2",
  "dumbbell decline twist fly",
  "dumbbell decline triceps extension",
  "dumbbell fly",
  "dumbbell finger curls",
  "dumbbell front raise v. 2",
  "dumbbell forward lunge triceps extension",
  "dumbbell fly on exercise ball",
  "dumbbell full can lateral raise",
  "dumbbell front raise",
  "dumbbell hammer curl on exercise ball",
  "dumbbell goblet squat",
  "dumbbell high curl",
  "dumbbell hammer curls (with arm blaster)",
  "dumbbell hammer curl v. 2",
  "dumbbell hammer curl",
  "dumbbell incline breeding",
  "dumbbell incline bench press",
  "dumbbell incline alternate press",
  "dumbbell incline biceps curl",
  "dumbbell incline hammer press on exercise ball",
  "dumbbell incline hammer curl",
  "dumbbell incline curl",
  "dumbbell incline curl v. 2",
  "dumbbell incline fly",
  "dumbbell incline fly on exercise ball",
  "dumbbell incline hammer press",
  "dumbbell incline one arm press",
  "dumbbell incline one arm hammer press on exercise ball",
  "dumbbell incline one arm hammer press",
  "dumbbell incline one arm fly",
  "dumbbell incline one arm lateral raise",
  "dumbbell incline one arm fly on exercise ball",
  "dumbbell incline inner biceps curl",
  "dumbbell incline one arm press on exercise ball",
  "dumbbell incline raise",
  "dumbbell incline shrug",
  "dumbbell incline rear lateral raise",
  "dumbbell incline shoulder raise",
  "dumbbell incline press on exercise ball",
  "dumbbell incline palm-in press",
  "dumbbell incline t-raise",
  "dumbbell incline row",
  "dumbbell incline triceps extension",
  "dumbbell incline twisted flyes",
  "dumbbell incline two arm extension",
  "dumbbell incline y-raise",
  "dumbbell iron cross",
  "dumbbell kickbacks on exercise ball",
  "dumbbell kickback",
  "dumbbell lateral raise",
  "dumbbell kneeling bicep curl exercise ball",
  "dumbbell lateral to front raise",
  "dumbbell lying alternate extension",
  "dumbbell lunge with bicep curl",
  "dumbbell lunge",
  "dumbbell lying elbow press",
  "dumbbell lying extension (across face)",
  "dumbbell lying one arm deltoid rear",
  "dumbbell lying on floor rear delt raise",
  "dumbbell lying hammer press",
  "dumbbell lying external shoulder rotation",
  "dumbbell lying femoral",
  "dumbbell lying one arm supinated triceps extension",
  "dumbbell lying one arm press v. 2",
  "dumbbell lying one arm press",
  "dumbbell lying pronation",
  "dumbbell lying one arm pronated triceps extension",
  "dumbbell lying one arm rear lateral raise",
  "dumbbell lying supination on floor",
  "dumbbell lying pronation on floor",
  "dumbbell lying pullover on exercise ball",
  "dumbbell lying supination",
  "dumbbell lying rear delt row",
  "dumbbell lying rear lateral raise",
  "dumbbell lying single extension",
  "dumbbell lying wide curl",
  "dumbbell neutral grip bench press",
  "dumbbell lying supine biceps curl",
  "dumbbell lying supine curl",
  "dumbbell lying triceps extension",
  "dumbbell one arm bench fly",
  "dumbbell one arm chest fly on exercise ball",
  "dumbbell one arm concentration curl (on stability ball)",
  "dumbbell one arm bent-over row",
  "dumbbell one arm decline chest press",
  "dumbbell one arm fly on exercise ball",
  "dumbbell one arm french press on exercise ball",
  "dumbbell one arm hammer preacher curl",
  "dumbbell one arm hammer press on exercise ball",
  "dumbbell one arm kickback",
  "dumbbell one arm incline chest press",
  "dumbbell one arm lateral raise with support",
  "dumbbell one arm lateral raise",
  "dumbbell one arm pullover on exercise ball",
  "dumbbell one arm prone hammer curl",
  "dumbbell one arm prone curl",
  "dumbbell one arm reverse wrist curl",
  "dumbbell one arm press on exercise ball",
  "dumbbell one arm reverse grip press",
  "dumbbell one arm reverse fly (with support)",
  "dumbbell one arm reverse preacher curl",
  "dumbbell one arm seated bicep curl on exercise ball",
  "dumbbell one arm seated hammer curl",
  "dumbbell one arm reverse spider curl",
  "dumbbell one arm seated neutral wrist curl",
  "dumbbell one arm shoulder press",
  "dumbbell one arm triceps extension (on bench)",
  "dumbbell one arm shoulder press v. 2",
  "dumbbell one arm standing hammer curl",
  "dumbbell one arm standing curl",
  "dumbbell one arm snatch",
  "dumbbell one arm zottman preacher curl",
  "dumbbell one leg fly on exercise ball",
  "dumbbell one arm wrist curl",
  "dumbbell over bench neutral wrist curl",
  "dumbbell over bench one arm neutral wrist curl",
  "dumbbell one arm upright row",
  "dumbbell over bench one arm reverse wrist curl",
  "dumbbell peacher hammer curl",
  "dumbbell palm rotational bent over row",
  "dumbbell over bench one arm wrist curl",
  "dumbbell over bench revers wrist curl",
  "dumbbell over bench wrist curl",
  "dumbbell palms in incline bench press",
  "dumbbell plyo squat",
  "dumbbell preacher curl",
  "dumbbell preacher curl over exercise ball",
  "dumbbell press on exercise ball",
  "dumbbell pronate-grip triceps extension",
  "dumbbell prone incline hammer curl",
  "dumbbell pullover",
  "dumbbell prone incline curl",
  "dumbbell pullover on exercise ball",
  "dumbbell raise",
  "dumbbell pullover hip extension on exercise ball",
  "dumbbell rear delt raise",
  "dumbbell push press",
  "dumbbell rear fly",
  "dumbbell rear lunge",
  "dumbbell revers grip biceps curl",
  "dumbbell rear lateral raise (support head)",
  "dumbbell rear lateral raise",
  "dumbbell rear delt row_shoulder",
  "dumbbell reverse grip incline bench one arm row",
  "dumbbell reverse fly",
  "dumbbell reverse bench press",
  "dumbbell reverse spider curl",
  "dumbbell reverse grip incline bench two arm row",
  "dumbbell rotation reverse fly",
  "dumbbell reverse grip row (female)",
  "dumbbell reverse wrist curl",
  "dumbbell seated alternate hammer curl on exercise ball",
  "dumbbell seated alternate front raise",
  "dumbbell seated alternate press",
  "dumbbell reverse preacher curl",
  "dumbbell romanian deadlift",
  "dumbbell scott press",
  "dumbbell seated alternate shoulder",
  "dumbbell seated bicep curl",
  "dumbbell seated bench extension",
  "dumbbell seated curl",
  "dumbbell seated bent arm lateral raise",
  "dumbbell seated bent over alternate kickback",
  "dumbbell seated bent over triceps extension",
  "dumbbell seated biceps curl to shoulder press",
  "dumbbell seated biceps curl (on stability ball)",
  "dumbbell seated calf raise",
  "dumbbell seated front raise",
  "dumbbell seated hammer curl",
  "dumbbell seated inner biceps curl",
  "dumbbell seated lateral raise",
  "dumbbell seated kickback",
  "dumbbell seated one arm kickback",
  "dumbbell seated neutral wrist curl",
  "dumbbell seated lateral raise v. 2",
  "dumbbell seated one arm bicep curl on exercise ball with leg raised",
  "dumbbell seated palms up wrist curl",
  "dumbbell seated one leg calf raise - palm up",
  "dumbbell seated one leg calf raise",
  "dumbbell seated one arm rotate",
  "dumbbell seated one leg calf raise - hammer grip",
  "dumbbell seated shoulder press (parallel grip)",
  "dumbbell seated reverse grip one arm overhead tricep extension",
  "dumbbell seated revers grip concentration curl",
  "dumbbell seated preacher curl",
  "dumbbell side bend",
  "dumbbell shrug",
  "dumbbell seated shoulder press",
  "dumbbell seated triceps extension",
  "dumbbell single leg split squat",
  "dumbbell single leg calf raise",
  "dumbbell side plank with rear fly",
  "dumbbell single arm overhead carry",
  "dumbbell single leg deadlift with stepbox support",
  "dumbbell side lying one hand raise",
  "dumbbell single leg squat",
  "dumbbell single leg deadlift",
  "dumbbell standing bent over one arm triceps extension",
  "dumbbell squat",
  "dumbbell standing bent over two arm triceps extension",
  "dumbbell standing alternate hammer curl and press",
  "dumbbell standing alternate overhead press",
  "dumbbell standing around world",
  "dumbbell standing alternate raise",
  "dumbbell standing alternating tricep kickback",
  "dumbbell standing concentration curl",
  "dumbbell standing biceps curl",
  "dumbbell standing front raise above head",
  "dumbbell standing calf raise",
  "dumbbell standing inner biceps curl v. 2",
  "dumbbell standing kickback",
  "dumbbell standing one arm concentration curl",
  "dumbbell standing one arm curl (over incline bench)",
  "dumbbell standing one arm curl over incline bench",
  "dumbbell standing one arm reverse curl",
  "dumbbell standing one arm extension",
  "dumbbell standing one arm palm in press",
  "dumbbell standing zottman preacher curl",
  "dumbbell standing reverse curl",
  "dumbbell standing preacher curl",
  "dumbbell standing overhead press",
  "dumbbell standing triceps extension",
  "dumbbell standing palms in press",
  "dumbbell step up single leg balance with bicep curl",
  "dumbbell sumo pull through",
  "dumbbell stiff leg deadlift",
  "dumbbell supported squat",
  "dumbbell step-up split squat",
  "dumbbell step-up lunge",
  "dumbbell step-up",
  "dumbbell straight leg deadlift",
  "dumbbell straight arm pullover",
  "dumbbell tate press",
  "dumbbell waiter biceps curl",
  "dumbbell upright row (back pov)",
  "dumbbell twisting bench press",
  "dumbbell upright row",
  "dumbbell tricep kickback with stork stance",
  "dumbbell upright shoulder external rotation",
  "dumbbell w-press",
  "dumbbell zottman curl",
  "exercise ball back extension with hands behind head",
  "dumbbells seated triceps extension",
  "elbow dips",
  "exercise ball alternating arm ups",
  "exercise ball back extension with arms extended",
  "dumbbell zottman preacher curl",
  "elevator",
  "dynamic chest stretch (male)",
  "elbow-to-knee",
  "elbow lift - reverse push-up",
  "exercise ball back extension with knees off ground",
  "exercise ball one leg prone lower body rotation",
  "exercise ball hip flexor stretch",
  "exercise ball hug",
  "exercise ball lat stretch",
  "exercise ball on the wall calf raise (tennis ball between knees)",
  "exercise ball back extension with rotation",
  "exercise ball lower back stretch (pyramid)",
  "exercise ball dip",
  "exercise ball on the wall calf raise",
  "exercise ball lying side lat stretch",
  "exercise ball on the wall calf raise (tennis ball between ankles)",
  "exercise ball one legged diagonal kick hamstring curl",
  "exercise ball pike push up",
  "exercise ball prone leg raise",
  "exercise ball seated hamstring stretch",
  "exercise ball seated triceps stretch",
  "exercise ball supine triceps extension",
  "ez bar reverse grip bent over row",
  "ez bar lying bent arms pullover",
  "ez bar seated close grip concentration curl",
  "ez bar standing french press",
  "ez barbell anti gravity press",
  "ez bar french press on exercise ball",
  "ez bar lying close grip triceps extension behind head",
  "ez barbell jm bench press",
  "ez barbell decline close grip face press",
  "ez barbell decline triceps extension",
  "ez barbell curl",
  "ez barbell close-grip curl",
  "ez barbell close grip preacher curl",
  "ez barbell incline triceps extension",
  "ez-bar biceps curl (with arm blaster)",
  "ez barbell reverse grip curl",
  "ez barbell reverse grip preacher curl",
  "ez barbell seated curls",
  "ez barbell spider curl",
  "ez barbell spider curl",
  "ez barbell seated triceps extension",
  "ez-bar close-grip bench press",
  "forward jump",
  "ez-barbell standing wide grip biceps curl",
  "floor fly (with barbell)",
  "finger curls",
  "flag",
  "flexion leg sit up (straight arm)",
  "farmers walk",
  "flutter kicks",
  "flexion leg sit up (bent knee)",
  "front lever reps",
  "full maltese",
  "frog planche",
  "frog crunch",
  "frankenstein squat",
  "front lever",
  "front plank with twist",
  "forward lunge (male)",
  "full planche",
  "full planche push-up",
  "gironda sternum chin",
  "glute bridge two legs on bench (male)",
  "glute bridge march",
  "groin crunch",
  "gorilla chin",
  "glute-ham raise",
  "hack one leg calf raise",
  "hack calf raise",
  "half sit-up (male)",
  "hands clasped circular toe touch (male)",
  "half knee bends (male)",
  "hands bike",
  "hamstring stretch",
  "hands reversed clasped circular toe touch (male)",
  "hanging straight leg hip raise",
  "hanging pike",
  "hanging oblique knee raise",
  "handstand",
  "hanging leg raise",
  "handstand push-up",
  "hanging leg hip raise",
  "hyperextension",
  "impossible dips",
  "hanging straight twisting leg hip raise",
  "hanging straight leg raise",
  "hug keens to chest",
  "hip raise (bent knee)",
  "high knee against wall",
  "hyght dumbbell fly",
  "hyperextension (on bench)",
  "incline leg hip raise (leg straight)",
  "incline push-up (on box)",
  "incline close-grip push-up",
  "incline push up depth jump",
  "inchworm",
  "inchworm v. 2",
  "incline push-up",
  "incline reverse grip push-up",
  "inverse leg curl (on pull-up cable machine)",
  "incline twisting sit-up",
  "intermediate hip flexor and quad stretch",
  "inverse leg curl (bench support)",
  "incline scapula push up",
  "inverted row",
  "inverted row on bench",
  "inverted row bent knees",
  "inverted row v. 2",
  "isometric chest squeeze",
  "inverted row with straps",
  "iron cross stretch",
  "jackknife sit-up",
  "isometric wipers",
  "jack burpee",
  "jack jump (male)",
  "janda sit-up",
  "kettlebell alternating renegade row",
  "kettlebell alternating press on floor",
  "jump rope",
  "jump squat",
  "jump squat v. 2",
  "kettlebell alternating hang clean",
  "kettlebell advanced windmill",
  "kettlebell alternating press",
  "kettlebell arnold press",
  "kettlebell double jerk",
  "kettlebell alternating row",
  "kettlebell double alternating hang clean",
  "kettlebell bottoms up clean from the hang position",
  "kettlebell double push press",
  "kettlebell bent press",
  "kettlebell figure 8",
  "kettlebell extended range one arm press on floor",
  "kettlebell double windmill",
  "kettlebell hang clean",
  "kettlebell double snatch",
  "kettlebell lunge pass through",
  "kettlebell goblet squat",
  "kettlebell front squat",
  "kettlebell one arm row",
  "kettlebell pistol squat",
  "kettlebell one arm push press",
  "kettlebell one arm floor press",
  "kettlebell one arm clean and jerk",
  "kettlebell one arm snatch",
  "kettlebell one arm jerk",
  "kettlebell one arm military press to the side",
  "kettlebell pirate supper legs",
  "kettlebell plyo push-up",
  "kettlebell seated press",
  "kettlebell seesaw press",
  "kettlebell seated two arm military press",
  "kettlebell sumo high pull",
  "kettlebell thruster",
  "kettlebell swing",
  "kettlebell two arm clean",
  "kettlebell turkish get up (squat style)",
  "kettlebell two arm row",
  "knee touch crunch",
  "kettlebell two arm military press",
  "kick out sit",
  "kettlebell windmill",
  "kipping muscle up",
  "l-pull-up",
  "kneeling jump squat",
  "kneeling plank tap shoulder (male)",
  "kneeling push-up (male)",
  "l-sit on floor",
  "kneeling lat stretch",
  "korean dips",
  "lever alternate leg press",
  "lean planche",
  "leg pull in flat bench",
  "leg up hamstring stretch",
  "left hook. boxing",
  "landmine 180",
  "landmine lateral raise",
  "lever bicep curl",
  "lever alternating narrow grip seated row",
  "lever back extension",
  "lever assisted chin-up",
  "lever bent over row",
  "lever calf press",
  "lever bent-over row with v-bar",
  "lever chest press",
  "lever donkey calf raise",
  "lever decline chest press",
  "lever chest press",
  "lever deadlift",
  "lever gripless shrug",
  "lever front pulldown",
  "lever gripless shrug v. 2",
  "lever hammer grip preacher curl",
  "lever gripper hands",
  "lever high row",
  "lever hip extension v. 2",
  "lever horizontal one leg press",
  "lever incline chest press",
  "lever kneeling twist",
  "lever kneeling leg curl",
  "lever incline chest press v. 2",
  "lever lateral raise",
  "lever lying two-one leg curl",
  "lever leg extension",
  "lever lying leg curl",
  "lever military press",
  "lever narrow grip seated row",
  "lever one arm lateral high row",
  "lever one arm lateral wide pulldown",
  "lever one arm bent over row",
  "lever overhand triceps dip",
  "lever one arm shoulder press",
  "lever preacher curl",
  "lever reverse grip preacher curl",
  "lever pullover",
  "lever reverse hyperextension",
  "lever seated calf press",
  "lever reverse grip lateral pulldown",
  "lever preacher curl v. 2",
  "lever rotary calf",
  "lever reverse grip vertical row",
  "lever reverse t-bar row",
  "lever seated good morning",
  "lever seated calf raise",
  "lever seated hip adduction",
  "lever seated crunch",
  "lever seated hip abduction",
  "lever seated dip",
  "lever seated crunch v. 2",
  "lever seated crunch (chest pad)",
  "lever seated leg curl",
  "lever seated fly",
  "lever seated leg raise crunch",
  "lever seated reverse fly",
  "lever seated row",
  "lever seated reverse fly (parallel grip)",
  "lever seated squat calf raise on leg press machine",
  "lever shoulder press",
  "lever shrug",
  "lever shoulder press v. 2",
  "lever shoulder press v. 3",
  "lever standing calf raise",
  "lever t bar row",
  "lever triceps extension",
  "lever standing chest press",
  "lever t-bar reverse grip row",
  "lever unilateral row",
  "london bridge",
  "low glute bridge on floor",
  "lunge with jump",
  "lower back curl",
  "lying (side) quads stretch",
  "lunge with twist",
  "lying elbow to knee",
  "lying leg raise flat bench",
  "medicine ball chest pass",
  "lying leg-hip raise",
  "march sit (wall)",
  "medicine ball catch and overhead throw",
  "machine inner chest press",
  "medicine ball chest push multiple response",
  "medicine ball chest push with run release",
  "medicine ball chest push single response",
  "mixed grip chin-up",
  "medicine ball supine chest throw",
  "modified hindu push-up (male)",
  "medicine ball chest push from 3 point stance",
  "medicine ball close grip push up",
  "medicine ball overhead slam",
  "negative crunch",
  "monster walk",
  "oblique crunch v. 2",
  "muscle-up (on vertical bar)",
  "mountain climber",
  "modified push up to lower arms",
  "muscle up",
  "neck side stretch",
  "narrow push-up on exercise ball",
  "one leg donkey calf raise",
  "one arm dip",
  "one arm chin-up",
  "one arm against wall",
  "oblique crunches floor",
  "olympic barbell triceps extension",
  "olympic barbell hammer curl",
  "one arm towel row",
  "one arm slam (with medicine ball)",
  "one leg floor calf raise",
  "one leg squat",
  "overhead triceps stretch",
  "pelvic tilt",
  "pike-to-cobra push-up",
  "outside leg kick push-up",
  "peroneals stretch",
  "otis up",
  "pelvic tilt into bridge",
  "potty squat with support",
  "potty squat",
  "posterior tibialis stretch",
  "plyo push up",
  "posterior step to overhead reach",
  "power clean",
  "power point plank",
  "prone twist on stability ball",
  "prisoner half sit-up (male)",
  "pull-in (on stability ball)",
  "push and pull bodyweight",
  "pull up (neutral grip)",
  "pull-up",
  "push-up (bosu ball)",
  "push to run",
  "push up on bosu ball",
  "push-up (on stability ball)",
  "push-up",
  "push-up plus",
  "push-up (wall) v. 2",
  "push-up close-grip off dumbbell",
  "push-up inside leg kick",
  "push-up medicine ball",
  "push-up on lower arms",
  "push-up (on stability ball)",
  "push-up (wall)",
  "rear decline bridge",
  "resistance band hip thrusts on knees (female)",
  "resistance band leg extension",
  "quarter sit-up",
  "raise single arm push-up",
  "resistance band seated biceps curl",
  "quads",
  "quick feet v. 2",
  "reclining big toe pose with rope",
  "push-up to side plank",
  "resistance band seated chest press",
  "rear deltoid stretch",
  "rear pull-up",
  "resistance band seated straight back row",
  "reverse grip machine lat pulldown",
  "reverse hyper on flat bench",
  "reverse dip",
  "resistance band seated hip abduction",
  "reverse crunch",
  "reverse grip pull-up",
  "reverse hyper extension (on stability ball)",
  "resistance band seated shoulder press",
  "reverse plank with leg lift",
  "rocking frog stretch",
  "ring dips",
  "rocky pull-up pulldown",
  "roller back stretch",
  "roller seated shoulder flexor depresor retractor",
  "roller body saw",
  "roller hip lat stretch",
  "roller hip stretch",
  "roller reverse crunch",
  "roller seated single leg shoulder flexor depresor retractor",
  "roller side lat stretch",
  "run",
  "rope climb",
  "runners stretch",
  "run (equipment)",
  "russian twist",
  "scapula dips",
  "seated calf stretch (male)",
  "seated glute stretch",
  "seated leg raise",
  "scapular pull-up",
  "scapula push-up",
  "scissor jumps (male)",
  "seated lower back stretch",
  "self assisted inverse leg curl (on floor)",
  "self assisted inverse leg curl",
  "self assisted inverse leg curl",
  "semi squat jump (male)",
  "seated piriformis stretch",
  "seated wide angle pose sequence",
  "short stride run",
  "seated side crunch (wall)",
  "shoulder grip pull-up",
  "side lying hip adduction (male)",
  "shoulder tap push-up",
  "side lying floor stretch",
  "side bridge hip abduction",
  "side bridge v. 2",
  "shoulder tap",
  "side hip abduction",
  "side hip (on parallel bars)",
  "side plank hip adduction",
  "side push-up",
  "side push neck stretch",
  "side-to-side chin",
  "side wrist pull stretch",
  "single arm push-up",
  "single leg bridge with outstretched leg",
  "side-to-side toe touch (male)",
  "single leg calf raise (on a dumbbell)",
  "single leg platform slide",
  "single leg squat (pistol) male",
  "sissy squat",
  "skater hops",
  "sit-up v. 2",
  "sit-up with arms on chest",
  "ski ergometer",
  "ski step",
  "sled 45в° leg press",
  "skin the cat",
  "sled 45в° calf press",
  "sled 45 degrees one leg press",
  "sled 45в° leg press (back pov)",
  "sled calf press on leg press",
  "sled 45в° leg wide press",
  "sled hack squat",
  "sled 45° leg press (side pov)",
  "sled closer hack squat",
  "sled forward angled calf raise",
  "sled one leg calf press on leg press",
  "smith behind neck press",
  "smith back shrug",
  "sled lying calf press",
  "sled lying squat",
  "smith bent over row",
  "smith bench press",
  "sledge hammer",
  "smith bent knee good morning",
  "smith hip raise",
  "smith full squat",
  "smith decline bench press",
  "smith deadlift",
  "smith chair squat",
  "smith close-grip bench press",
  "smith decline reverse-grip press",
  "smith hack squat",
  "smith front squat (clean grip)",
  "smith incline bench press",
  "smith incline shoulder raises",
  "smith incline reverse-grip press",
  "smith leg press",
  "smith low bar squat",
  "smith machine decline close grip bench press",
  "smith machine bicep curl",
  "smith narrow row",
  "smith machine reverse decline close grip bench press",
  "smith machine incline tricep extension",
  "smith one arm row",
  "smith reverse-grip press",
  "smith one leg floor calf raise",
  "smith rear delt row",
  "smith reverse calf raises",
  "smith reverse calf raises",
  "smith reverse grip bent over row",
  "smith squat",
  "smith seated shoulder press",
  "smith seated wrist curl",
  "smith shrug",
  "smith sprint lunge",
  "smith seated one leg calf raise",
  "smith shoulder press",
  "smith standing back wrist curl",
  "smith single leg split squat",
  "smith standing military press",
  "smith wide grip bench press",
  "snatch pull",
  "smith standing leg calf raise",
  "smith standing behind head military press",
  "smith wide grip decline bench press",
  "sphinx",
  "spine stretch",
  "smith sumo squat",
  "spider crawl push up",
  "smith upright row",
  "smith toe raise",
  "spell caster",
  "stability ball crunch (full range hands behind head)",
  "squat on bosu ball",
  "split squats",
  "stalder press",
  "squat to overhead reach with twist",
  "spine twist",
  "squat jerk",
  "squat to overhead reach",
  "standing archer",
  "standing behind neck press",
  "standing calves",
  "standing calf raise (on a staircase)",
  "standing hamstring and calf stretch with strap",
  "standing pelvic tilt",
  "standing calves calf stretch",
  "standing lateral stretch",
  "stationary bike walk",
  "straddle maltese",
  "straight leg outer hip abductor",
  "straddle planche",
  "stationary bike run v. 3",
  "standing single leg curl",
  "star jump (male)",
  "standing wheel rollerout",
  "swing 360",
  "suspended push-up",
  "superman push-up",
  "tire flip",
  "suspended reverse crunch",
  "triceps dip",
  "suspended row",
  "suspended split squat",
  "suspended abdominal fallout",
  "three bench dip",
  "trap bar deadlift",
  "swimmer kicks v. 2 (male)",
  "triceps dips floor",
  "upward facing dog",
  "tuck crunch",
  "upper back stretch",
  "two toe touch (male)",
  "twin handle parallel grip lat pulldown",
  "triceps dip (bench leg)",
  "triceps press",
  "triceps dip (between benches)",
  "twisted leg raise",
  "twisted leg raise (female)",
  "triceps stretch",
  "twist hip lift",
  "v-sit on floor",
  "walk elliptical cross trainer",
  "vertical leg raise (on parallel bars)",
  "walking high knees lunge",
  "walking lunge",
  "walking on stepmill",
  "walking on incline treadmill",
  "weighted decline sit-up",
  "weighted close grip chin-up on dip cage",
  "weighted bench dip",
  "weighted cossack squats (male)",
  "weighted crunch",
  "weighted donkey calf raise",
  "weighted hanging leg-hip raise",
  "weighted front raise",
  "weighted drop push up",
  "weighted hyperextension (on stability ball)",
  "weighted front plank",
  "weighted kneeling step with swing",
  "weighted pull-up",
  "weighted round arm",
  "weighted muscle up",
  "weighted russian twist",
  "weighted lunge with swing",
  "weighted muscle up (on bar)",
  "weighted one hand pull up",
  "weighted russian twist (legs up)",
  "weighted overhead crunch (on stability ball)",
  "weighted sissy squat",
  "weighted russian twist v. 2",
  "weighted seated bicep curl (on stability ball)",
  "weighted straight bar dip",
  "weighted standing hand squeeze",
  "weighted side bend (on stability ball)",
  "weighted standing curl",
  "weighted stretch lunge",
  "weighted seated twist (on stability ball)",
  "weighted squat",
  "weighted svend press",
  "weighted triceps dip on high parallel bars",
  "wide hand push up",
  "wheel run",
  "wide grip pull-up",
  "weighted tricep dips",
  "wheel rollerout",
  "weighted three bench dips",
  "wide grip rear pull-up",
  "wide-grip chest dip on high parallel bars",
  "wind sprints",
  "wrist circles",
  "world greatest stretch",
  "wrist rollerer"
  ]

const workoutNamesListSelect = workoutNames.map(name => {
  return { label: name,  value: name }
})
export default workoutNamesListSelect