name: Deploy Node Application

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ process.env }} -p ${{  }}
      - name: Build Docker Image
        run: docker build -t sujithvarughese/simpler-fitness-server .
      - name: Publish Image to docker hub
        run: docker push sujithvarughese/simpler-fitness-server:latest

deploy:
  needs: build
  runs-on: self-hosted
  steps:
    - name: Pull image from docker hub
      run: docker pull sujithvarughese/simpler-fitness-server:latest
    - name: Run docker container
      run: docker run -d -p 3000:3000 --name nodejs-app-container -e
