export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const SET_IS_LOADING = "SET_IS_LOADING"
export const SET_AUTH_STATE = "SET_AUTH_STATE"
export const SHOW_REGISTER_MODAL = "SHOW_REGISTER_MODAL"

export const SET_FAVORITES = "SET_FAVORITES"